#!/usr/bin/env python3

import argparse
import math
import re
from pathlib import Path


VERTEX_RE = re.compile(
    r"\{Q16\(([-+0-9.eE]+)f?\),\s*"
    r"Q16\(([-+0-9.eE]+)f?\),\s*"
    r"Q16\(([-+0-9.eE]+)f?\)\}"
)
TRIANGLE_RE = re.compile(r"\{(\d+),\s*(\d+),\s*(\d+)\}")


def extract_array(source: str, declaration: str) -> str:
    start = source.index(declaration)
    start = source.index("{", start) + 1
    end = source.index("};", start)
    return source[start:end]


def generate(source_path: Path, output_path: Path) -> None:
    source = source_path.read_text(encoding="utf-8")
    vertex_block = extract_array(source, "const Thd_point_t rose_vertices[]")
    triangle_block = extract_array(source, "const tri_t rose_tris[]")

    vertices = [tuple(map(float, match.groups())) for match in VERTEX_RE.finditer(vertex_block)]
    triangles = [tuple(map(int, match.groups())) for match in TRIANGLE_RE.finditer(triangle_block)]

    if not vertices or not triangles:
        raise ValueError("failed to parse rose vertices or triangles")

    lines = [
        "/* Generated by generate_face_normals.py. Do not edit manually. */",
        "const int16_t rose_face_normals_q14[][3] = {",
    ]

    for i0, i1, i2 in triangles:
        ax, ay, az = vertices[i0]
        bx, by, bz = vertices[i1]
        cx, cy, cz = vertices[i2]

        ux, uy, uz = bx - ax, by - ay, bz - az
        vx, vy, vz = cx - ax, cy - ay, cz - az
        nx = uy * vz - uz * vy
        ny = uz * vx - ux * vz
        nz = ux * vy - uy * vx
        length = math.sqrt(nx * nx + ny * ny + nz * nz)

        if length > 0.0:
            scale = 16384.0 / length
            nx = max(-16384, min(16384, round(nx * scale)))
            ny = max(-16384, min(16384, round(ny * scale)))
            nz = max(-16384, min(16384, round(nz * scale)))
        else:
            nx = ny = nz = 0

        lines.append(f"    {{{nx:6d}, {ny:6d}, {nz:6d}}},")

    lines.extend(["};", ""])
    output_path.write_text("\n".join(lines), encoding="ascii", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Q14 face normals for rose.c")
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.source, args.output)


if __name__ == "__main__":
    main()
