// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------------- //
// st77xx_parallel_byte //
// -------------------- //

#define st77xx_parallel_byte_wrap_target 0
#define st77xx_parallel_byte_wrap 3

static const uint16_t st77xx_parallel_byte_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x7008, //  1: out    pins, 8         side 0     
    0xb942, //  2: nop                    side 1 [1] 
    0x0000, //  3: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program st77xx_parallel_byte_program = {
    .instructions = st77xx_parallel_byte_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config st77xx_parallel_byte_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + st77xx_parallel_byte_wrap_target, offset + st77xx_parallel_byte_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

